### ISSUE TITLE
Nao é uma issue so uma sugestao de adicao a lib

### ISSUE THREAD

**Issue by ir4ever** [mtobbias/365apps-pack-validador#10]
Olá, primeiramente muito boa essa lib a uso em varios projetos. Eu fiz uma modificacao nela que talvez faça sentido para ela. Eu precisava de uma validacao booleana e meio que criei algo generico em cima disso que é receber um bool q se verdadeiro esta valido, bem simples mesmo, mas me foi bem util.
Codigo que adicionei ao arquivo:

String? _ifTrueMsg;
  bool? _ifTrue;

Validador ifTrue(bool validacao, {String msg = DEFAULT_MESSAGE}) {
    this._ifTrueMsg = msg;
    this._ifTrue = validacao;
    return this;
  }
//validar bool
    if (this._ifTrue != null) {
      try {
        if (!isNotNull || !this._ifTrue!) {
          _erros.add(this._ifTrueMsg);
        }
      } catch (e) {
        _erros.add(this._ifTrueMsg);
      }
    }

**Comment by mtobbias** [comment]
@ir4ever obrigado pela colaboração, lib atualizada com a sua feature
