### ISSUE TITLE
Warning with  Flutter version 1.20.4 - 15/09/2020

### ISSUE THREAD

**Issue by EvincarSN** [mtobbias/365apps-pack-validador#2]
Ao atualizar o Flutter para versão 1.20.4 me apareceu um _warning_ referente a lib validadores-1.0.2:

_..\.pub-cache\hosted\pub.dartlang.org\validadores-1.0.2\android\src\main\kotlin\br\com\u365apps\pack\validadores\validadores\ValidadoresPlugin.kt:20:50: warning: 'getFlutterEngine(): FlutterEngine' is deprecated. Deprecated in Java
    channel = MethodChannel(flutterPluginBinding.getFlutterEngine().getDartExecutor(), "validadores")_

**Comment by mtobbias** [comment]
https://github.com/mtobbias/365apps-pack-validador/releases/tag/1.0.4
